server:
  port: 8081
  tomcat:
    max-threads: 10
eureka:
  server:
    enableSelfPreservation : true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  user:
    name: test
    password: test