spring:
  application:
    name: service-cat
  datasource:
    url: jdbc:mysql://localhost:3306/lightingdetection?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 61000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8081/eureka/
server:
  port: 8091
security:
  user:
    name: test
    password: test
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
